services:
  db:
    image: postgres:17
    container_name: bd_vanessa_fontalvo_puertadeoro-postgres

    environment:
      POSTGRES_DB: bd_vanessa_fontalvo_puertadeoro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    ports:
      - "5433:5432"

    volumes:
      - bd_vanessa_fontalvo_puertadeoro-db-data:/var/lib/postgresql/data

volumes:
  bd_vanessa_fontalvo_puertadeoro-db-data: